# Generated by Django 5.2.5 on 2025-10-18 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('projects', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('place_of_supply', models.CharField(max_length=255)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('our_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, default=9.0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=9.0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=18.0, max_digits=10)),
                ('pdf', models.FileField(blank=True, upload_to='invoices/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
        ),
    ]
