# Generated by Django 5.2.5 on 2025-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
