# Generated by Django 5.2.5 on 2025-10-19 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_remove_employee_reporting_manager_manager_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_phase', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('plan_type', models.CharField(blank=True, max_length=255)),
                ('plan_number', models.CharField(max_length=255)),
                ('revision', models.CharField(default='A', max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('estimated_hours', models.PositiveIntegerField()),
                ('completion', models.PositiveIntegerField()),
                ('regulatory_approval', models.BooleanField(default=False)),
                ('dependencies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
