# Generated by Django 5.2.5 on 2025-09-16 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_remove_employee_reporting_manager_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('budget', models.IntegerField(blank=True)),
                ('timeline', models.CharField()),
                ('follow_up_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
