# Generated by Django 5.2.5 on 2025-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='timeline',
            field=models.CharField(max_length=255),
        ),
    ]
