# Generated by Django 5.2.5 on 2025-10-16 14:49

import django.db.models.deletion
import utils.pay_period
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_remove_employee_reporting_manager_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_month', models.CharField(default=utils.pay_period.current_month_period, max_length=20)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='payslips/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
