# Generated by Django 5.2.5 on 2025-10-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pdf',
        ),
    ]
