# Generated by Django 5.2.5 on 2025-10-16 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('imo_number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('flag_state', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_society', models.CharField(blank=True, max_length=255, null=True)),
                ('class_notation', models.CharField(blank=True, max_length=255, null=True)),
                ('build_year', models.PositiveIntegerField(blank=True, null=True)),
                ('shipyard', models.CharField(blank=True, max_length=255, null=True)),
                ('length_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gross_tonnage', models.PositiveIntegerField(blank=True, null=True)),
                ('net_tonnage', models.PositiveIntegerField(blank=True, null=True)),
                ('deadweight', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
